### ISSUE TITLE
create cmdline utility to generate and verify hashes

### ISSUE THREAD

**Issue by ibotty** [inejge/pwhash#17] opened 2022-10-06 12:14 UTC
It would be great to have a small cli utility that can generate and verify hashes.

Of course it could be a different package, but I think this might be a fine spot in this library, because

 * the name `pwhash` is great for that utility,
 * when adding different algorithms (e.g. argon2*), it can be distributed in tandem.

**Comment by inejge** [comment] 2022-10-29 20:08
Sorry for the delay in answering this one, I noticed it when fresh and then it slipped my mind. A binary could be added to the crate, but the set of hashing algorithms is fixed; by design, I wish to keep just the historic and present system hashes on Unix-like systems. I notice you've mentioned argon2 -- I wouldn't add it to the crate, so a hashing program in the crate couldn't provide it.

A separate crate is, then, what I'd recommend. I think that `hashpw` is still available, and is also a fine name.

I'll close this issue and the pull request.

**Closed as completed by inejge** 2022-10-29 20:08 UTC
