### ISSUE TITLE
bcrypt - Bad hash

### ISSUE THREAD

**Issue by ghost** [inejge/pwhash#7] opened 2017-07-11 14:22 UTC
So, yes **bcrypt** works fine using it with the same libary (pwhash), but when I try to use it on different libaries, those hashes are invalid?!

![344260f7-9fda-43b3-bd77-d89a263cc29e](https://user-images.githubusercontent.com/10303701/28073102-13bd4b12-6655-11e7-8fd5-0428337be185.png)

**Why are that bad hashes?**

**Comment by inejge** [comment] 2017-07-11 14:41
Could you paste the failing hash as text, not an image? Also, what's the URL of the service which you've used for checking?

**Comment by ghost** [comment] 2017-07-11 19:34
@inejge `$2b$08$0AL.Cm0PXvytOKvZS8uwde8zkKzV1OwRGXaIylmYrbpgqPF.DKg7C`

**Comment by inejge** [comment] 2017-07-11 20:05
What's the cleartext password for that hash? I notice that a) the hash is not the same as the one partially displayed above, and b) verifying with the cleartext value "d" fails.

**Comment by ghost** [comment] 2017-07-11 20:29
It failed everytime. Wether I use `h` or `jdjejejdidiejsnwoodjebsiud2j` as password. There seems to be something wrong with the salt stuff..

**Comment by inejge** [comment] 2017-07-11 21:30
Well, I've found the site you've used ([bcrypt-generator.com](https://bcrypt-generator.com/)), and made a few checks using the following simple generator, which creates a bcrypt hash from its first argument:

```rust
extern crate pwhash;

use std::env;

use pwhash::bcrypt;

fn main() {
    println!("{}", bcrypt::hash(&env::args().nth(1).unwrap()).unwrap());
}
```

They all worked. E.g., for the cleartext password `h` the program generated the hash `$2b$08$khyvSkhhSKzLqk0x16Y8L.d6S4rERwRWv0RFwv01J4vZdwnoKyvbO` in one run (try those values).

I'm not sure what problem you're encountering, but I don't think that the bcrypt functions are to blame.

**Comment by inejge** [comment] 2017-07-12 05:57
Since I couldn't reproduce the failure, I'm going to close this issue.

**Closed as completed by inejge** 2017-07-12 05:57 UTC

**Comment by ghost** [comment] 2017-07-12 09:04
Sorry for that. Was a error on my code. And thank you for keeping this libary alive.
